version: '3.0'

services:

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./../dist:/var/www/fleyt.stub
      - ./nginx/conf.d:/etc/nginx/conf.d
